apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: deploy-petstore-trigger-template
  namespace: petstore
spec:
  params:
    - name: imageName
    - name: storageClass
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
          pipeline.openshift.io/started-by: build0
        generateName: deploy-petstore-
        labels:
          tekton.dev/pipeline: deploy-petstore
        namespace: petstore
      spec:
        params:
          - name: deployment-name
            value: petstore
          - name: image-tag
            value: $(tt.params.imageName)
          - name: storageclass-name
            value: $(tt.params.storageClass)
        pipelineRef:
          name: deploy-petstore
        resources: []
        status: null
        workspaces:
        - name: shared-ws
          configMap:
            name: petstore-db-files